#!/bin/sh

set -e
set -x

if /usr/bin/apt-cache policy python3-pyqt5 | grep "Installed: (none)"; then
  sudo apt update
  sudo apt install python3-pyqt5
  sudo apt --fix-broken install
fi

if /usr/bin/apt-cache policy python3-stem | grep "Installed: (none)"; then
  sudo apt update
  sudo apt install python3-stem
fi
